プルリク１回目
Ritsuag/review pull request #1
Opened 2023-12-18 23:59 UTC by Ritsuag

お願いします。

2023-12-19 00:08 UTC, atsushiL requested changes
@Ritsuag 

ご確認お願いします〜

2023-12-19 00:08 UTC, atsushiL commented on review.html
> +<p>1回目</p>
ここは1回目じゃなくて 2回目にしてください！

2023-12-19 00:08 UTC, atsushiL commented on review.html
> +<p>1回目</p>
ファイル末尾に改行が入っていないようなので、修正してください！

2023-12-19 05:37 UTC, Ritsuag commented
@atsushiL プルリク再レビューお願いします。
・レビュー２回目のため１回目→２回目へ修正。

・誤ってmasterの方に２回目の文言を修正したものを更新してしまいました。
　変更箇所がわかるようにコメントアウトで記述しています。

・ファイル末尾に改行が無かったため追記したものを載せあげています。

2023-12-22 07:47 UTC, atsushiL commented on review.html
> +<p>1回目</p>
以下コミットにて修正しました。

[e77024a](https://github.com/Ritsuag/review/pull/1/commits/e77024aab5005f700785865d7abebb1514d8ab5f)

2023-12-22 07:50 UTC, Ritsuag commented on review.html
> +<p>1回目</p>
以下コミットにて修正しました。

2023-12-22 07:53 UTC, atsushiL commented on review.html
> +<p>1回目</p>
> なんでこのようにしたか教えてください！

VSCode の設定不備が原因でした！

以下コミットにて修正しました
-------------------------

2023-12-22 07:57 UTC, atsushiL commented on review.html
> +<p>1回目</p>
テスト通知

2023-12-22 07:58 UTC, atsushiL commented on review.html
> +<p>1回目</p>
@Ritsuag 
テスト通知

2023-12-22 08:00 UTC, atsushiL approved these changes

2023-12-22 08:00 UTC, merged